baseURL = '//odyssey346.dev'
languageCode = 'en-us'
title = 'Odyssey346'
theme = 'odyssey'

[languages]
  [languages.en]
    title = "Odyssey346"
    subtitle = "Unprofessional computer user"
    keywords = ""
    copyright = "© 2022 - present Odyssey346. Theme based off of the Hello Friend Hugo theme."
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02.01.2006"
    dateFormatList = "02.01.2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Odyssey346"
      logoHomeLink = "/"
    [languages.en.params.about]
      WelcomeText = "Hi👋 I'm "
      WelcomeTextHighlight = "Odyssey346"
      WelcomeTextAfterHighlight = "!"
      Subtext = "Developer, gamer and kind-of sysadmin, and a lazy person."
      Subtext3 = "Below are my blog posts. Happy reading!"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/Odyssey346"
      [[languages.en.menu.main]]
        identifier = "matrix"
        name = "Matrix"
        url = "https://matrix.to/#/@odyssey:projectsegfau.lt"

#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 3
#  [[menu.main]]
#    identifier = "discord"
#    name = "Discord"
#    url = "https://discord.gg/GdsCQX5US2"
#    weight = 4

#[params]
#  author = "Odyssey346"
#  description = "Unprofessional computer user"
#  avatar = "avatar.png"
#  menu_item_separator = " - "
#  [[params.social]]
#    icon = "github"
#    name = "GitHub"
#    url = "https://github.com/Odyssey346"
#  [[params.social]]
#    icon = "twitter"
#    name = "Pleroma (Fediverse)"
#    url = "https://social.projectsegfau.lt/Odyssey346"
#  [[params.social]]
#    icon = "message-circle"
#    name = "Matrix"
#   url = "https://matrix.to/#/@odyssey346:ohai.su"
#  [[params.social]]
#    icon = "at-sign"
#    name = "Email"
#    url = "/mail/"
#
#  [params.style]
#    darkestColor = "#151515"
#    darkColor = "#252525"
#    lightColor = "#d6d6d6"
#    lightestColor = "#d3d3d3"
#    primaryColor = "#17ce5c"
#
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
