baseURL = '//odyssey346.github.io'
languageCode = 'en-us'
title = 'Odyssey346'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/GdsCQX5US2"
    weight = 4   

[params]
  author = "Odyssey346"
  description = "Unprofessional computer user"
  avatar = "avatar.png"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Odyssey346"
  [[params.social]]
    icon = "twitter"
    name = "Pleroma (Fediverse)"
    url = "https://social.projectsegfau.lt/Odyssey346"
  [[params.social]]
    icon = "message-circle"
    name = "Matrix"
    url = "https://matrix.to/#/@odyssey346:ohai.su"
  [[params.social]]
    icon = "at-sign"
    name = "Email"
    url = "/mail/"

  [params.style]
    darkestColor = "#151515"
    darkColor = "#252525"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#17ce5c"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
