name: Deploy to IPFS (web3.storage)

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "./public"
      - run: echo ${{ steps.web3.outputs.cid }}
      - run: echo ${{ steps.web3.outputs.url }}